token = '359898542:AAGLWmglnnbWROTxze_h0vv8bYjVtOJSVIc'

CREATE_JOURNEY = {
    'NAME': 0,
    'DEPARTURE_PLACE': 1,
    'DESTINATION': 2,
    'DEPARTURE_DATE': 3,
    'ARRIVAL_DATE': 4,
    'BUDGET': 5,
    'PUBLICITY_AND_ADDING': 6
}